---
  - name: "Setup Environment"
    hosts: localhost
    connection: local
    tasks:
    - name: "Install the lastet version of vim, git, rxvt, tmux, powerline, and etc"
      package:
        name:
          - git
          - vim
          - emacs
          - rxvt-unicode
          - python3-pip
          - fonts-powerline
          - tmux
          - xsel
          - docker.io
          - htop
          - ffmpeg
          - curl
        state: latest

    - name: "Install chromium"
      snap:
        name: chromium

    - name: "Install powerline-status"
      pip:
        name: powerline-status

    - name: "Create symbolic links"
      file:
        src: '/home/pahagon/dot/{{ item.src }}'
        dest: '/home/pahagon/{{ item.dest }}'
        owner: pahagon
        group: pahagon
        state: link
      loop:
        - { src: "linux/Xresources", dest: ".Xdefault"     }
        - { src: "linux/Xinitrc",    dest: ".Xinitrc"      }
        - { src: "linux/Xmodmap",    dest: ".Xmodmap"      }
        - { src: "linux/Xresources", dest: ".Xresources"   }
        - { src: "tmux/tmux.conf",   dest: ".tmux.conf"    }
        - { src: "bash/locale",      dest: ".locale"       }
        - { src: "bash/inputrc",     dest: ".inputrc"      }
        - { src: "bash/login",       dest: ".bash_login"   }
        - { src: "bash/logout",      dest: ".bash_logout"  }
        - { src: "bash/profile",     dest: ".bash_profile" }
        - { src: "bash/rc",          dest: ".bashrc"       }
        - { src: "git/gitignore",    dest: ".gitignore"    }
        - { src: "git/gitconfig",    dest: ".gitconfig"    }
        - { src: "emacs",            dest: ".emacs.d"      }
        - { src: "vim",              dest: ".vim"          }
        - { src: "bin",              dest: "bin"          }

    - name: "Clone asdf"
      git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: '/home/pahagon/.asdf'
        version: v0.8.0

    - name: "Add pahagon user to docker group"
      user:
        name: pahagon
        state: present
        groups: docker,sudo
        append: yes

